import type { Metadata } from "next";
import { Playfair_Display_SC, Urbanist } from "next/font/google";
import "./globals.css";

const fontSerif = Playfair_Display_SC({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  display: "swap",
  preload: true,
});

const fontSans = Urbanist({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSerif.variable} ${fontSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
